### ISSUE TITLE
Where do I define ZB_ED_ROLE? (TZ-724)

### ISSUE THREAD

**Issue by Runepx4** [espressif/esp-zigbee-sdk#302] opened 2024-03-29 22:18 UTC
When I try to compile the Temperature Sensor example I get an error stating that I need to define **ZV_ED_ROLE** in the idf.py menuconfig. This error makes sense based on the code, but where do I do that (and what would be the standard value for the temperature sensor example)?

```
#if !defined ZB_ED_ROLE
#error Define ZB_ED_ROLE in idf.py menuconfig to compile sensor (End Device) source code.
#endif
```

**Comment by 0rion12** [comment] 2024-03-30 20:07
I got exactly the same problem with the light example. 
As mentionned in the error, I checked the menuconfig, but I did not see any parameter related to ZB_ED_ROLE or zigbee.

**Comment by amidarius** [comment] 2024-03-31 16:46
Same here and also during compilation of HA_color_dimmable_light.

`#error Define ZB_ZCZR in idf.py menuconfig to compile light (Router) source code.`

and HA_on_off_light

` #error Define ZB_ED_ROLE in idf.py menuconfig to compile light (End Device) source code.`

For each example i did this :

`idf.py set-target esp32h2`

followed with this

`idf.py build`

ESP-IDF v5.1.2

**Comment by xieqinan** [comment] 2024-04-01 04:29
@Runepx4 , @0rion12 , @amidarius ,

Regarding the issue, I'm sorry, but we have encountered a CI issue that needs to be fixed. As a result, there is a  error in the release version that matches esp-zigbee-lib and esp-zboss-lib. We will fix it as soon as possible.

**Comment by amidarius** [comment] 2024-04-01 06:54
Changed and confirming that **HA_temperature_sensor** example now compiles and seen by Z2M after flashing the ESP32H2 device.

![HA_temperature_sensor 2024-04-01 085045](https://github.com/espressif/esp-zigbee-sdk/assets/29826378/1370e4f0-5f3e-47b0-8547-0fbe437ec99d)
![HA_temperature_sensor 2024-04-01 085151](https://github.com/espressif/esp-zigbee-sdk/assets/29826378/42544c51-f2a0-43eb-aed3-253a1d4c8e29)

**Comment by xieqinan** [comment] 2024-04-01 11:12
Hello,

This issue has been resolved. Could you please update the esp-zigbee-sdk to version 1.2.2 and test it again? If the problem is resolved, please close this issue. Thank you.

**Comment by 0rion12** [comment] 2024-04-01 13:22
For me version 1.2.2 is working.

**Comment by 0rion12** [comment] 2024-04-01 13:30
> Changed and confirming that **HA_temperature_sensor** example now compiles and seen by Z2M after flashing the ESP32H2 device.
> 
> ![HA_temperature_sensor 2024-04-01 085045](https://private-user-images.githubusercontent.com/29826378/318360401-1370e4f0-5f3e-47b0-8547-0fbe437ec99d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQ0NDQsIm5iZiI6MTcxMTk3NDE0NCwicGF0aCI6Ii8yOTgyNjM3OC8zMTgzNjA0MDEtMTM3MGU0ZjAtNWYzZS00N2IwLTg1NDctMGZiZTQzN2VjOTlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyMjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNzBmMDZiZWZjNmYyOWUwYmZiMmRiYjdiODMxZDZiOGY5ZjVjZTM5ZjhhYmJmYTM0OTk1ZGZhNDY1NjU0NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sqFIqSObNFfU5ScIj9gLfbvKEkdv3bLtWRXPjp7evBI) ![HA_temperature_sensor 2024-04-01 085151](https://private-user-images.githubusercontent.com/29826378/318360409-42544c51-f2a0-43eb-aed3-253a1d4c8e29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQ0NDQsIm5iZiI6MTcxMTk3NDE0NCwicGF0aCI6Ii8yOTgyNjM3OC8zMTgzNjA0MDktNDI1NDRjNTEtZjJhMC00M2ViLWFlZDMtMjUzYTFkNGM4ZTI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyMjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiN2NmMzEzZTA2ZGFkMzYzZTk1YWRhZjc1ZWE2OTBlMWQxMzE3OTU2NDE4MmJjNDZiODQ1M2RiM2NjMzAwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oouzXWb5FDEAWasbeb-RlaqHOuaQ19HAKPa8Sso-yEc)

Hello, I try to use the light example. I use Z2M with HA. I am able to make it join the network. 
But then since it is not a supported device, I got nothing under the expose tab.  
<img width="1037" alt="image" src="https://github.com/espressif/esp-zigbee-sdk/assets/61796302/e205d6fc-e99b-4163-9d8a-d687ea4fb92c">
<img width="1040" alt="image" src="https://github.com/espressif/esp-zigbee-sdk/assets/61796302/69fa475b-aef9-45a8-8ca3-b6503a8b107f">

How did you manage to get data from your device ? Did you create a custom config somewhere ?

**Comment by lhespress** [comment] 2024-04-02 06:19
@0rion12 `Z2M`, what do you mean [zigbee2mqtt](https://github.com/zigbee2mqtt) ? BTW, Could you create a new issue because of this issue has been resolved?

**Closed** 2024-04-03 09:11 UTC
