### ISSUE TITLE
Read ADC data during light-sleep (TZ-611)

### ISSUE THREAD

**Issue by vedatbotuk** [espressif/esp-zigbee-sdk#236] opened 2024-02-01 09:49 UTC
### Answers checklist.

- [x] I have read the documentation [ESP Zigbee SDK Programming Guide](https://docs.espressif.com/projects/esp-zigbee-sdk) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) and ESP Zigbee libs ([esp-zboss-lib](https://components.espressif.com/components/espressif/esp-zboss-lib) and [esp-zigbee-lib](https://components.espressif.com/components/espressif/esp-zigbee-lib)) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3-dev-582-gab03c2ea13

### esp-zigbee-lib version.

1.0.9

### esp-zboss-lib version.

1.0.9

### Espressif SoC revision.

ESP32-H2

### What is the expected behavior?

Read ADC data during light-sleep

### What is the actual behavior?

I would like to measure the battery voltage via ADC input. If I do not use sleep mode, it works.
But if I use light sleep it does not work.
![grafik](https://github.com/espressif/esp-zigbee-sdk/assets/72791621/02c45eee-ab68-4f71-8284-6a3ef8b2d890)

### Steps to reproduce.

1. Step
2. Step
3. Step
...

**Comment by chshu** [comment] 2024-02-01 11:39
I think the ADC operation during light sleep is not supported yet. You can acquire a sleep lock for the ADC operation, please try out the follow code:

```
esp_pm_lock_handle_t s_adc_lock;
esp_pm_lock_create(ESP_PM_CPU_FREQ_MAX, 0, "adc", &s_adc_lock);
esp_pm_lock_acquire(s_adc_lock);
// do the ADC operation here
esp_pm_lock_release(s_adc_lock);
```

**Comment by vedatbotuk** [comment] 2024-02-01 13:35
No change. Unfortunately, this extension does not help either.

**Comment by diazmanuel** [comment] 2024-02-01 13:57
hello @chshu,
I have the same problem as @vedatbotuk, I can't read the adc correctly, the only time the adc read is correct is when the read is done at the same time as the zigbee keepalive signal, then the problem is that the code you posted above does not work, it does not keep the chip awake to read

**Comment by kelin6** [comment] 2024-02-02 07:29
@vedatbotuk @diazmanuel  In the esp-idf, the ADC light sleep retention feature for the esp32h2 has not been supported yet. As a result, ADC register backup and restoration are not supported. Therefore, after waking up, the ADC registers are not restored.

If you really need to use the ADC during light sleep, you can try the following approach: after waking up, reinitialize the ADC, read ADC data, deinitialize the ADC, and then go back to sleep.

**Comment by vedatbotuk** [comment] 2024-02-02 07:44
@kelin6 , Do you know when this feature will be implemented? Is there a plan?

**Comment by diazmanuel** [comment] 2024-02-02 12:38
hello @kelin6

> If you really need to use the ADC during light sleep, you can try the following approach: after waking up, reinitialize the ADC, read ADC data, deinitialize the ADC, and then go back to sleep.

 i already try that but sometimes works and sometimes not, will you add this feature ? in my case i dont need to read on the sleep state but i wish i could only initialize 1 time and the read locking the chip in the awake state.

**Comment by agustinebrecht** [comment] 2024-02-06 13:26
Hello, @kelin6 I have the same problem as @diazmanuel  @vedatbotuk. The solution you propose to measure after sleep in the zigbee handler is a problem and it still gives me the same result of 4081. I clarify that I am using the esp32H2 for a low energy product.

**Comment by kelin6** [comment] 2024-02-18 02:52
@agustinebrecht  @diazmanuel @vedatbotuk 
For your convenience in testing, I am uploading my test code [light_sleep.zip](https://github.com/espressif/esp-zigbee-sdk/files/14320904/light_sleep.zip). Based on the esp-zigbee-sdk light sleep example, I have added ADC-related interfaces. The testing environment is as follows:

esp-idf: ab03c2ea1
esp-zigbee-sdk: 1.1.1
CHIP: ESP32H2
When GPIO3 is connected to 3.3V, the ADC read data is 3360.
When GPIO3 is connected to GND, the ADC read data is 0.

![image](https://github.com/espressif/esp-zigbee-sdk/assets/39639038/046a50be-13ab-49cd-952e-6198d6b3ff02)

Please use the test code I provided above for testing. If there are any other issues during testing, feel free to provide your test code for further analysis.

**Comment by vedatbotuk** [comment] 2024-03-02 13:34
Thanks for your code @kelin6 . That works fine. I have another questions. If I want to read the GPIO pin during light sleep, it doesn't work properly either.

I use following code in ```void app_main(void)```
```
gpio_set_direction(INPUT_PIN, GPIO_MODE_INPUT);
gpio_set_pull_mode(INPUT_PIN, GPIO_PULLUP_ONLY);
```

And I try to check the GPIO Input, if is up or down with a while loop.
```
gpio_get_level(INPUT_PIN)
```
I get wrong input while running light sleep. It trigers without any reason.
I tried also after ```esp_zb_sleep_now();```, but it did not work. Do you have any solution for that.

**Comment by kelin6** [comment] 2024-03-12 06:20
@vedatbotuk I am uploading my test code [light_sleep.zip](https://github.com/espressif/esp-zigbee-sdk/files/14568043/light_sleep.zip). Based on the esp-zigbee-sdk light sleep example, I have added
GPIO get level related interfaces. The testing environment is as follows:

esp-idf: 0c47128
esp-zigbee-sdk: 1.2.0


CHIP: ESP32H2
When GPIO3 is connected to 3.3V, the `gpio_get_level` is 1.
When GPIO3 is connected to GND, the `gpio_get_level` is 0.

![image](https://github.com/espressif/esp-zigbee-sdk/assets/39639038/aa2d1433-a55d-4621-a6ec-c96816592ef3)

**Comment by vedatbotuk** [comment] 2024-03-13 22:11
In my case I need some sleep time, otherwise ```gpio_get_level(INPUT_PIN)``` does not work correct.
In following out put you can see that.
```
I (12710) WATERLEAK_CHECK: Water detected
I (12760) WATERLEAK_CHECK: Water alarm released
I (18746) SIGNAL: Zigbee can sleep
I (26755) SIGNAL: Zigbee can sleep
I (26756) WATERLEAK_CHECK: Water detected
I (26806) WATERLEAK_CHECK: Water alarm released
I (34755) SIGNAL: Zigbee can sleep
I (34756) WATERLEAK_CHECK: Water detected
I (34806) WATERLEAK_CHECK: Water alarm released
I (42769) SIGNAL: Zigbee can sleep
I (42769) WATERLEAK_CHECK: Water detected
I (42820) WATERLEAK_CHECK: Water alarm released
I (50768) SIGNAL: Zigbee can sleep
I (50768) WATERLEAK_CHECK: Water detected
I (50818) WATERLEAK_CHECK: Water alarm released
I (65864) SIGNAL: Zigbee can sleep
I (68374) SIGNAL: Zigbee can sleep
I (71392) SIGNAL: Zigbee can sleep
I (71393) WATERLEAK_CHECK: Water detected
I (71443) WATERLEAK_CHECK: Water alarm released
I (77420) SIGNAL: Zigbee can sleep
I (85429) SIGNAL: Zigbee can sleep
I (85430) WATERLEAK_CHECK: Water detected
I (85480) WATERLEAK_CHECK: Water alarm released
I (93428) SIGNAL: Zigbee can sleep
I (93429) WATERLEAK_CHECK: Water detected
````

I just add some sleep time befor or after ```esp_zb_sleep_now()``` and then works fine.
```
    case ESP_ZB_COMMON_SIGNAL_CAN_SLEEP:
        ESP_LOGI(TAG_SIGNAL_HANDLER, "Zigbee can sleep");
         vTaskDelay(pdMS_TO_TICKS(100)); /*This sleep is necessary for the get_button()*/
         get_gpio_level();
        esp_zb_sleep_now();
        break;
```

**Comment by kelin6** [comment] 2024-03-15 06:24
@vedatbotuk 
Based on my code, it seems to be working fine. I'm not quite sure why you need to call vTaskDelay again. 

Could you provide the simplest possible code based on our esp-zigbee-light sleep example that can reproduce the issue on your end? This will help us investigate further.

**Comment by Drippin101** [comment] 2024-03-19 19:17
when i try to run the light_sleep code provided i get the problem: 'test_get_gpio_level' defined but not used [-Wunused-function]. Any fixes?

**Comment by kelin6** [comment] 2024-04-24 06:59
@Drippin101 You can try this:  After waking up the device, read the GPIO level and send a custom cluster containing the GPIO level data to Home Assistant.

**Comment by lxz946786639** [comment] 2024-07-12 06:54
> @agustinebrecht @diazmanuel @vedatbotuk For your convenience in testing, I am uploading my test code [light_sleep.zip](https://github.com/espressif/esp-zigbee-sdk/files/14320904/light_sleep.zip). Based on the esp-zigbee-sdk light sleep example, I have added ADC-related interfaces. The testing environment is as follows:
> 
> esp-idf: ab03c2ea1 esp-zigbee-sdk: 1.1.1 CHIP: ESP32H2 When GPIO3 is connected to 3.3V, the ADC read data is 3360. When GPIO3 is connected to GND, the ADC read data is 0.
> 
> ![image](https://private-user-images.githubusercontent.com/39639038/305681234-046a50be-13ab-49cd-952e-6198d6b3ff02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjYzNzksIm5iZiI6MTcyMDc2NjA3OSwicGF0aCI6Ii8zOTYzOTAzOC8zMDU2ODEyMzQtMDQ2YTUwYmUtMTNhYi00OWNkLTk1MmUtNjE5OGQ2YjNmZjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA2MzQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmM2FmMzhmZDIzYmFlOTFhMzdiYTUwOTU3MDVjOTY2ZmJkNDA0YTEwNTUyZDFiMmZmMTJiMmZlMzI3NThmMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fc-PduYMRo0i9izEhG86qzeFyT_xmSJjYUncsi7JOgY)
> 
> Please use the test code I provided above for testing. If there are any other issues during testing, feel free to provide your test code for further analysis.

Hello, what is the ADC voltage input range of ESP32H2? Thanks

**Comment by chshu** [comment] 2024-09-29 07:48
@vedatbotuk There were some fixes in the ADC retention after sleep, could you test again using IDF [v5.3.1](https://github.com/espressif/esp-idf/releases/tag/v5.3.1), let us know if you still see any issues.

**Comment by vedatbotuk** [comment] 2024-09-30 07:58
Ok @chshu, I will check it.

**Comment by vedatbotuk** [comment] 2024-10-22 12:40
Hi @chshu 
I could test it today.
For me works with IDF v5.2.3 fine.

**Comment by chshu** [comment] 2024-12-19 09:47
@vedatbotuk Thanks for the update. Closing.

**Closed by chshu** 2024-12-19 09:47 UTC
Labels: Bug
